linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - bodyclose
    - noctx
    - unconvert

linters-settings:
  govet:
    check-shadowing: true
    enable-all: true

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
